Feature/kr creation
jschuhmann47/projectMap-Frontend pull request #25
Opened 2024-09-29 16:22 UTC by DiegoAnazonian

2024-10-01 02:49 UTC, pablo092 commented on src/views/OKRView/components/KeyResult/indexv2.jsx
> +  const shoeProgress = () => {
Typo error en shoe?

2024-10-02 00:37 UTC, T-J-Antonio requested changes

2024-10-02 00:37 UTC, T-J-Antonio commented on src/views/OKRView/components/KeyResult/indexv2.jsx
> +    <ModalV2 width={900} isOpen={isOpen} background={'#FFFFFF'} onClose={onClose} title={data.description}>
le dejaría el background color original

2024-10-02 00:37 UTC, T-J-Antonio commented on src/components/inputs/SelectPriority/index.jsx
> +export default function SelectPriority(props) {
este componente no se usa

2024-10-02 00:37 UTC, T-J-Antonio commented on src/views/OKRView/components/KeyResult/KrForm.jsx
> +                fieldLabel="Linea base"
```suggestion
                fieldLabel="Línea base"
```

2024-10-02 00:37 UTC, T-J-Antonio commented on src/views/OKRView/components/KeyResult/KrForm.jsx
> +                }}
acá podría usarse el componente auxiliar que definiste más arriba. De todos modos hay que agregarle estilos (fuente Fira Sans y borde negro) para que se lleve bien con el resto de inputs

2024-10-02 00:37 UTC, T-J-Antonio commented on src/views/OKRView/indexv2.jsx
> +              fieldLabel="Linea Base"
```suggestion
              fieldLabel="Línea Base"
```

2024-10-02 03:26 UTC, DiegoAnazonian commented on src/views/OKRView/components/KeyResult/indexv2.jsx
> +  const shoeProgress = () => {
No entendi, te aparece un error ?

2024-10-02 23:03 UTC, T-J-Antonio approved these changes

2024-10-02 23:03 UTC, merged