politica-contrasena-fuerte-al-crear-cuenta
jschuhmann47/projectMap-Frontend pull request #55
Opened 2024-10-08 04:05 UTC by pablo092

2024-10-08 23:57 UTC, T-J-Antonio requested changes
es cierto que la descripción de la tarjeta es medio escueta :P, pero esto también habría que aplicarlo cuando se recupera la contraseña

2024-10-10 01:46 UTC, T-J-Antonio approved these changes

2024-10-16 21:45 UTC, jschuhmann47 commented on src/helpers/validateField.js
> +  const passwordRegex = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/;
`HELLO123!_sas` por ej no matchea, puede ser?

2024-10-16 21:49 UTC, jschuhmann47 commented on src/helpers/validateField.js
> +  const passwordRegex = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/;
Este creo q anda
`^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@#$%^&-+=()!? "]).{8,128}$`

2024-10-16 21:50 UTC, jschuhmann47 requested changes

2024-10-16 21:50 UTC, jschuhmann47 commented on src/helpers/validateField.js
> +  const passwordRegex = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/;
.

2024-10-20 16:43 UTC, jschuhmann47 approved these changes

2024-10-27 20:52 UTC, merged