[DRAFT] feat: crea container and get tools
jschuhmann47/projectMap-Frontend pull request #57
Opened 2024-10-10 01:35 UTC by DiegoAnazonian

Rediseño de las etapas

2024-10-14 00:15 UTC, T-J-Antonio requested changes

2024-10-14 00:15 UTC, T-J-Antonio commented on src/redux/selectors/project.selector.js
> +        console.log({porters})
eliminar log

2024-10-14 00:15 UTC, T-J-Antonio commented on src/views/ProjectView/styles.js
> +  minWidth: '500px'
aumentar el ancho y hacerlo fijo

2024-10-14 00:15 UTC, T-J-Antonio commented on src/views/ProjectView/styles.js
> +  gridTemplateColumns: '5fr 1fr',
aumentaría el ancho de la primera columna así el tachito está más cerca del borde

2024-10-14 00:15 UTC, T-J-Antonio commented on src/containers/StageContainer.jsx
> +            <AddIcon />
cambiar por "@mui/icons-material/AddCircle"

2024-10-14 00:15 UTC, T-J-Antonio commented on src/redux/selectors/project.selector.js
> +export const selectorByStage = {
Cambiar títulos a los siguientes:
Análisis Porter
Análisis PESTEL
Análisis FODA
Matrices Ansoff
Matrices McKinsey
Cuestionarios
OKRs
Balanced scorecards

2024-10-14 11:21 UTC, jschuhmann47 commented
Que las requests al back las haga dentro de cada etapa

2024-10-14 11:23 UTC, jschuhmann47 requested changes
Ver comentario abajo

2024-10-16 00:45 UTC, DiegoAnazonian commented on src/views/ProjectView/styles.js
> +  gridTemplateColumns: '5fr 1fr',
ahi quedo disminuyendo la segunda en 0.5

2024-10-16 00:46 UTC, DiegoAnazonian commented on src/views/ProjectView/styles.js
> +  minWidth: '500px'
lo aumente en 100, mepa que muy grande queda feo.. pero lo subo y podemos definir otro valor

2024-10-16 21:41 UTC, T-J-Antonio requested changes
si podés sacá las requests de las herramientas de la tab de etapas, o sea que sólo se hagan dentro de la vista de una etapa

2024-10-20 16:30 UTC, T-J-Antonio approved these changes

2024-10-20 20:55 UTC, T-J-Antonio requested changes

2024-10-20 20:55 UTC, T-J-Antonio commented on src/containers/StageContainer.jsx
> +  };
wait, acá no está lo del padre que agregamos en el ProjectContainer, habría que sumarlo acá tb

2024-10-21 08:48 UTC, T-J-Antonio approved these changes

2024-10-21 11:30 UTC, jschuhmann47 approved these changes

2024-10-21 11:37 UTC, merged