Feature/not measurable kr
jschuhmann47/projectMap-Frontend pull request #61
Opened 2024-10-14 01:21 UTC by DiegoAnazonian

2024-10-17 00:33 UTC, T-J-Antonio requested changes

2024-10-17 00:33 UTC, T-J-Antonio commented on src/views/OKRView/styles.js
> +  marginTop: '15px'
faltaría agregarle la fuente

2024-10-17 00:33 UTC, T-J-Antonio commented on src/views/OKRView/components/KeyResult/indexv2.jsx
> +      return data.keyStatus?.length >= 1 ? `${data.keyStatus?.length} ítem` : `${data.keyStatus?.length} ítems`;
creo que sería al revés jajaj

2024-10-19 18:12 UTC, DiegoAnazonian commented on src/views/OKRView/components/KeyResult/indexv2.jsx
> +      return data.keyStatus?.length >= 1 ? `${data.keyStatus?.length} ítem` : `${data.keyStatus?.length} ítems`;
cuando tenes razon, tenes razon.

2024-10-19 18:12 UTC, DiegoAnazonian commented on src/views/OKRView/styles.js
> +  marginTop: '15px'
agregado "Fira Sans"

2024-10-21 09:19 UTC, T-J-Antonio approved these changes

2024-10-21 11:30 UTC, merged